// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	ConfigureProcessConfigurationOperation       OperationName = "ConfigureProcessConfiguration"
	ConfigureProcessConfigurationSecretOperation OperationName = "ConfigureProcessConfigurationSecret"
	ConfigureScheduleOperation                   OperationName = "ConfigureSchedule"
	CreateProcessConfigurationOperation          OperationName = "CreateProcessConfiguration"
	CreateScheduleOperation                      OperationName = "CreateSchedule"
	DeleteProcessConfigurationOperation          OperationName = "DeleteProcessConfiguration"
	DeleteScheduleOperation                      OperationName = "DeleteSchedule"
	GetProcessConfigurationByIdOperation         OperationName = "GetProcessConfigurationById"
	GetProcessConfigurationsOperation   OperationName = "GetProcessConfigurations"
	GetScheduleByIdOperation                     OperationName = "GetScheduleById"
	GetSchedulesOperation               OperationName = "GetSchedules"
)
