// Code generated by ogen, DO NOT EDIT.
package v1

type ConfigureProcessConfigurationRes interface {
	configureProcessConfigurationRes()
}

type ConfigureProcessConfigurationSecretRes interface {
	configureProcessConfigurationSecretRes()
}

type ConfigureScheduleRes interface {
	configureScheduleRes()
}

type CreateProcessConfigurationRes interface {
	createProcessConfigurationRes()
}

type CreateScheduleRes interface {
	createScheduleRes()
}

type DeleteProcessConfigurationRes interface {
	deleteProcessConfigurationRes()
}

type DeleteScheduleRes interface {
	deleteScheduleRes()
}

type GetProcessConfigurationByIdRes interface {
	getProcessConfigurationByIdRes()
}

type GetProcessConfigurationsRes interface {
	getProcessConfigurationsByAccountRes()
}

type GetScheduleByIdRes interface {
	getScheduleByIdRes()
}

type GetSchedulesRes interface {
	getSchedulesByAccountRes()
}
